name: day4-test

on:
    push:
        branches:
            - main
env:
    DOCKER_HUB_URL: ${{ secrets.DOCKER_HUB_URL }}
jobs:
  dev:
    runs-on: [self-hosted]
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - name: Deploy dev
        run:  echo ${{ vars.NAME }}
      - run: fdsufsdfs
  int:
    needs: dev
    if: ${{ needs.dev.result != 'success' }}
    runs-on: [self-hosted]
    environment: int
    steps:
      - uses: actions/checkout@v4
      - name: Deploy int
        run:  echo ${{ vars.NAME }}
  prod:
    needs: int
    if: ${{ needs.int.result != 'success' }}
    runs-on: [self-hosted]
    environment: prod
    steps:
      - uses: actions/checkout@v4
      - name: Deploy prod
        run:  echo ${{ vars.NAME }}
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
