name: day4-test

on:
    push:
        branches:
            - main

jobs:
  dev:
    runs-on: [ubuntu-latest]
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - name: Deploy dev
        run:  echo ${{ env.NAME }}
  int:
    needs: dev
    runs-on: [ubuntu-latest]
    environment: int
    steps:
      - uses: actions/checkout@v4
      - name: Deploy int
        run:  echo ${{ env.NAME }}
  prod:
    needs: int
    runs-on: [ubuntu-latest]
    environment: prod
    steps:
      - uses: actions/checkout@v4
      - name: Deploy prod
        run:  echo ${{ env.NAME }}
