name: day4

on:
    push:
        branches:
            - main

jobs:
  dev:
    runs-on: [self-hosted]
    outputs:
        environment: 'Development'
    steps:
      - uses: actions/checkout@v4
      - name: Deploy dev
        run: echo ${{ env.NAME }}
  int:
    needs: dev
    runs-on: [self-hosted]
    outputs:
        environment: 'Development'
    steps:
      - uses: actions/checkout@v4
      - name: Deploy int
        run: echo ${{ env.NAME }}
  prod:
    needs: int
    runs-on: [self-hosted]
    outputs:
        environment: 'Development'
    steps:
      - uses: actions/checkout@v4
      - name: Deploy prod
        run: echo ${{ env.NAME }}
